// This is a pre-bundled single-file version of the Express server.
// Generated by: npx esbuild server/src/index.ts --bundle --platform=node --format=esm --outfile=api/server.mjs --external:adm-zip --external:simple-git --external:multer
import app from './server.mjs';

export default app;
